### ISSUE TITLE
Suggest providing a `as` function for matrices or data.frame

### ISSUE THREAD

**Issue by epurdom** [drisso/SingleCellExperiment#10]
It would be nice to have a `as` command that would take a matrix or data.frame directly to a `SingleCellExperiment` class, i.e. `as(mat,"SingleCellExperiment")` where `mat` is a matrix.

I am trying this out for my package and for methods dispatch, I am frequently having to do 

```
setMethod(
  f = "myFunction",
  signature = "matrix",
  definition = function(object,...){myFunction(as(object,"SummarizedExperiment"))}
)
setMethod(
  f = "myFunction",
  signature = "SummarizedExperiment",
  definition = function(object,...){myFunction(as(object,"SingleCellExperiment"))}
)
```

It would be nice to be able to do just the first without the second on cases where it was appropriate. (I know its a bit trivial since I could also use the SingleCellExperiment constructor directly on a matrix, but just a thought)

Elizabeth Purdom

**Comment by LTLA** [comment]
Was there already an `as` method for coercing a matrix into a _SummarizedExperiment_ object?

```r
library(SummarizedExperiment) # 1.8.0
x <- matrix(rnorm(1000), ncol=10)
se <- as(x, "SummarizedExperiment")
# Error in as(x, "SummarizedExperiment") : 
#  no method or default for coercing “matrix” to “SummarizedExperiment”
```

If you can convince the _SummarizedExperiment_ maintainers to put in an `as` method, then we'll do the same for _SingleCellExperiment_. Otherwise it becomes confusing that you can coerce to a matrix to a _SingleCellExperiment_ but not to its base classes (technically _RangedSummarizedExperiment_).

**Comment by epurdom** [comment]
Sorry, my mistake. It was something I created internally and forgot about it!

**Comment by LTLA** [comment]
Closing this, unless there is a good reason not to.
