### ISSUE TITLE
Requires R version >=3.5

### ISSUE THREAD

**Issue by siamakz** [drisso/SingleCellExperiment#11]
Why????

**Comment by LTLA** [comment]
Because `R CMD BiocCheck` complains if that version requirement isn't listed. I assume that the idea is to force everyone to use the latest version of R (for their own good), and to protect us developers from having to deal with bugs arising from subtle differences in behaviour between R versions. 

If you're using _SingleCellExperiment_ from this repository, you should be running R-devel anyway. Otherwise you should be using the Bioconductor release version, which only requires `>= 3.4`.

**Comment by siamakz** [comment]
Using latest version of R on a personal machine is viable. But for the large scRNA-seq data people usually use clusters, and the clusters update R versions at slower paces. So it is not a bad idea to give a bit of freedom to users!

**Comment by LTLA** [comment]
I always update my version of R on the institute cluster, and I don't even have admin rights, so it's never been a problem with me. And freedom is always a double-edged sword - from the _BiocCheck_ vignette:

> ... BiocCheck checks to make sure that the R version specified matches the version currently used by Bioconductor. This prevents the package from being used in earlier versions of R, which is not recommended and is a frequent cause of user confusion

In general, there's a choice between users getting annoyed about having to update R, and then updating R, and everything working fine; **or** everyone (developers/users) wasting a whole lot of time figuring out whether unexpected behaviour for a package is due to the code in the package itself or the version of R. The brief annoyance in the first option is better than the chronic grief of the second option, especially given that the solution to the problem in the second option would be to update R anyway. 

The "current R version" policy is enforced throughout the Bioconductor ecosystem via `biocLite`, so if you don't like it, you're arguing with the wrong person - take it up with the core team.
