### ISSUE TITLE
Provide `as.matrix` S3 method

### ISSUE THREAD

**Issue by scottgigante** [drisso/SingleCellExperiment#26]
Many analysis functions that I would like to use on my `SingleCellExperiment` natively take a matrix or data frame as input. Would it be possible / sensible to define `as.matrix` and `as.data.frame` methods for this object to simplify the transfer to functions that expect such input?

**Comment by PeteHaitch** [comment]
I don't think it's possible or advisable.
What parts of the *SingleCellExperiment* would you expect transferred?

I think it pays to be explicit: e.g., passing the function `counts(sce))` or `logcounts(sce)` or `reducedDim(sce, "PCA")` as an argument; you may need to wrap that in a call to `as.data.frame()` or `as.matrix()` since `counts()`, `logcounts()`, and `reducedDim()` can in principal return a matrix-like object if the data are stored in such a way (e.g., a *dgCMatrix* or *HDF5Matrix*).

Really, I think effort should be the other way around, i.e. encouraging those other analysis functions to accept a *SingleCellExperiment* (assuming they are single-cell omics-specific methods and not just general statistical routines like regression). See many of the functions in **scran**, for example, which define a *SingleCellExperiment* method as well as an *ANY* method, which typically works for anything sufficiently matrix-like.

Alternatively, for the scenario you mention, I'd write a small wrapper function around the method I want to use that accepts a *SingleCellExperiment* as input and extracts the relevant data as a *matrix* or *data.frame* as appropriate.

**Comment by LTLA** [comment]
I concur with all of @PeteHaitch's suggestions.

**Comment by scottgigante** [comment]
Thanks for the detailed explanation @PeteHaitch. For novice users (like me!) would it be worth adding the S3 function purely to explain this in the form of an error message? My process ran as follows:

1. Pass SingleCellExperiment into function - unintuitive error message
2. Run `as.matrix` - method not defined.
3. Type `my_experiment$` and hit tab, look for something called `data`.
4. Type `my_experiment@` and hit tab, look for something called `data`.
5. Google "how to extract matrix from SingleCellExperiment"

A snippet of what I'm suggesting:
```
as.matrix.SingleCellExperiment <- function(x, ...) {
  stop("Error in as.matrix(x) : no method for coercing this S4 class to a matrix. Try counts(x), logcounts(x) or reducedDim(x).")
}
```

**Comment by LTLA** [comment]
A couple of points here. First, if the problem is really that much of a problem, then it should be implemented at the _SummarizedExperiment_ level. SEs are used much more frequently and widely than SCEs, so any systematic issue with the misinterpretation of the data structure would have manifested with the former.

This brings me to the second point, which is that the process that you've described is already the correct way to handle things. **1** is to be expected - a function that doesn't support SE input will naturally fail. **2** is also to be expected, as a SE is not a matrix, it stores matrices. I don't know why you would ever do **3** or **4**; so at this point, you're left with **5** (or, y'know, reading the docs), which leads you to the correct solution. Clearly, this was not sufficiently arduous that the core team felt the need to add any finger-wagging `as.matrix` method for SEs. 

From a more pragmatic perspective, there are millions of ways for users to stuff up. To add guardrails for every possible inappropriate combination of methods would be a maintenance nightmare. Today it's `as.matrix`, tomorrow it's some tidyverse incompatibility, next week - who knows?

**Comment by scottgigante** [comment]
Okay, fair enough. I had wrongly pinned SCE as essentially a matrix class and maybe misunderstood its purpose somewhat. Thanks for the explanation.

**Comment by PeteHaitch** [comment]
The figure below is a conceptual view of the *SummarizedExperiment* class (taken from the ['SummarizedExperiment for Coordinating Experimental Assays, Samples, and Regions of Interest' vignette](https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html). 
It pays to understand this because the *SingleCellExperiment* class builds on it.

![SummarizedExperiment](https://docs.google.com/feeds/download/drawings/Export?id=1kiC8Qlo1mhSnLDqkGiRNPSo6GWn3C2duBszCFbJCB-g&exportFormat=svg)

As Aaron notes, you can learn about the specifics of the *SingleCellExperiment* class by reading the documentation and vignettes:

- Run `help("SingleCellExperiment", "SingleCellExperiment")` in R
- [SummarizedExperiment for Coordinating Experimental Assays, Samples, and Regions of Interest](https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html)
- [An introduction to the SingleCellExperiment class](https://bioconductor.org/packages/release/bioc/vignettes/SingleCellExperiment/inst/doc/intro.html)
- [Developing around the SingleCellExperiment class](https://bioconductor.org/packages/release/bioc/vignettes/SingleCellExperiment/inst/doc/devel.html)

**Comment by drisso** [comment]
I think this figure is the key to understand the class for most novice users, and I think we should do a better job in SingleCellExperiment to point people to it, either by adding a modified version to the vignette or by pointing users more explicitly to the SummarizedExperiment vignette.

When I have a minute, I will try to implement this.

**Comment by LTLA** [comment]
Use the `Biocpkg` command to include links in the vignette.
