### ISSUE TITLE
could not find function "altExp<-"

### ISSUE THREAD

**Issue by ghost** [drisso/SingleCellExperiment#39]
Hello,

I get an error when I try to add an assay through 'altExp'.

```> altExp(citeseq_sce, "ADT") <- SummarizedExperiment(assay = list(counts = adt_cellHash))
Error in altExp(citeseq_sce, "ADT") <- SummarizedExperiment(assay = list(counts = adt_cellHash)) : 
  could not find function "altExp<-"```

**Comment by LTLA** [comment]
Are you using the Bioconductor devel [version](https://bioconductor.org/packages/devel/bioc/html/SingleCellExperiment.html)?

**Comment by ghost** [comment]
Yes, I downloaded the development version and I still get the same error. 

Any help is much appreciated. Thanks

**Comment by LTLA** [comment]
Just because you downloaded it, doesn't mean that you're actually using it.

If you download a package, you have to load it in with `library()`. But if you've already loaded an old version of the package, calling `library()` will not overwrite that old version in your R session. So you have to restart R and call `library(SingleCellExperiment)` to get the new version in your session.

**Comment by ghost** [comment]
Hi Aaron

Thanks for the solution.. It works now. I guess I should have tried that first before coming here. Apologies for asking such a trivial issue. 

Many thanks!
