### ISSUE TITLE
Propagation of row/colnames into assay data

### ISSUE THREAD

**Issue by davismcc** [drisso/SingleCellExperiment#5]
Hi Davide,

I was recently surprised when I accessed the `rownames` and `colnames` of `object@assays$data$logcounts`, where `object` is a `SingleCellExperiment` object. I had changed the object `rownames` (something like `rownames(object)  <- toupper(rownames(object))` and I found that the `rownames(object)` was no longer identical to `rownames(object@assays$data$logcounts)`.

Does that indicate a problem with rownames (and perhaps colnames) being propagated to assay elements? Or am I missing something here?

Best,
Davis

**Comment by LTLA** [comment]
Well, you shouldn't be using `@` at all. Inside `SummarizedExperiment` objects, dimnames are not stored in the assay elements, but are slapped on when those elements are extracted via `assay`. For example:

```r
example(SingleCellExperiment)
rownames(sce) <- paste0("Gene", seq_len(nrow(sce)))
identical(rownames(sce), rownames(assay(sce))) # TRUE
identical(rownames(sce), rownames(counts(sce))) # TRUE
identical(rownames(sce), rownames(logcounts(sce))) # TRUE
```

Otherwise we'd have to update every assay element every time we changed the object's dimnames.
