### ISSUE TITLE
Remove non-used slots

### ISSUE THREAD

**Issue by jgarces02** [drisso/SingleCellExperiment#51]
Hi @drisso, 

Thanks for so usefull class! That's a very (simply, I hope) question: is there any way to remove those slots not used in my `SingleCellExperiment` (for example, the `spikeNames(0)` one? 

Thanks in advance for your help. Regards.

**Comment by LTLA** [comment]
You can't "remove" slots from a class. They are always there, just empty. Otherwise, downstream code would have to check whether the slot exists before trying to access it, and at that point, the concept of a class falls apart - we might as well stuff data into a list and work with that.

In any case, the point is moot because the latest version of the package does not have a dedicated slot for spike-ins. This concept has now been generalized to the `altExps()` idea.

**Comment by jgarces02** [comment]
Perfectly logical. Thanks anyway!
