### ISSUE TITLE
Special field for gene symbols

### ISSUE THREAD

**Issue by lambdamoses** [drisso/SingleCellExperiment#70]
Seurat and scanpy by default use gene symbols, though I'm not sure what they do when multiple Ensembl IDs match the same gene symbol. Scanpy reads in both gene symbols and Ensembl IDs but uses gene symbols as variable names and puts Ensembl IDs in a variable metadata column. For SCE, when you read in output from Cell Ranger or Space Ranger, by default the row names are Ensembl IDs and gene symbols are in a `rowData` column. However, in practice, users (at least me) prefer to show the more human readable gene symbols in plots and outputs in general. I kind of find it annoying to explicitly use the `swap_rownames` argument in `scater` plotting functions every single time. Is it possible to put an optional special field in `int_metadata` indicating which column in `rowData` has the gene symbols when the rownames are Ensembl IDs so downstream functions would get gene symbols from that column? I still prefer to use Ensembl IDs behind the scene as they're more unequivocal on what genomic regions they refer to than gene symbols. When one symbol matches multiple Ensembl IDs, then issue a warning.

**Comment by PeteHaitch** [comment]
Personally, it seems like too small a feature to justify changing the class definition.

Updating an S4 class definition, especially a widely used and well-established one, should not be undertaken lightly.
When an S4 class definition is updated, the serialized instances of that class using the old definition are no longer compatible with the new definition i.e. potential headaches for lots of downstream users and developers.
The Bioconductor core team have developed some tools to help with a limited set of the consequences of updating an S4 class definition ([**updateObject**](https://bioconductor.org/packages/updateObject/)), but as they note it's a tedious process and it does not cover objects 'in the wild'.
The vignette provides some more details about this issue.

I too prefer to have gene symbols as feature names in plots.
I usually ensure this is by using `scuttle::uniquifyFeatureNames()` at the beginning of an analysis to set the rownames as the gene symbol (when it's unique) and otherwise append the the Ensembl ID to the gene symbol (as well as keeping the original Ensembl ID as a column in the _rowData_).
You might also find that more convenient than specifying the `swap_rownames` argument when creating plots with **scater**.

``` r
suppressPackageStartupMessages(library(scater))
uniquifyFeatureNames(
  ID=paste0("ENSG0000000", 1:5),
  names=c("A", NA, "B", "C", "A")
)
#> [1] "A_ENSG00000001" "ENSG00000002"   "B"              "C"             
#> [5] "A_ENSG00000005"
```

<sup>Created on 2023-08-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by LTLA** [comment]
probably someone could write a helper function in **scuttle** that streamlines the (1) calling of `uniquifyFeatureNames`, (2) moving of the Ensembl IDs to `rowData` and (3) replacement of the row names by the output of `uniquifyFeatureNames` into a single line with sensible defaults.

**Comment by lambdamoses** [comment]
OK, so I'll close this issue. It could be an issue in `DropletUtils` to add an argument to `read10xCounts` to set uniquified gene symbols as the row names and place Ensembl IDs in `rowData`, more like what scanpy does. I understand why you don't want to change SCE; I get how annoying Seurat's frequent changes to the object structure gets.
